calaveracustomer_homepage:
    pattern:  /
    defaults: { _controller: calaveracustomerBundle:Default:index }

calaveracustomer_homepage:
    pattern:  /newsletter
    defaults: { _controller: calaveracustomerBundle:Newsletter:index }

calaveracustomer_homepage:
    pattern:  /newsletter/test
    defaults: { _controller: calaveracustomerBundle:Newsletter:test }
  