parameters:
#    calaveracustomer.example.class: calavera\customerBundle\Example

services:
#    calaveracustomer.example:
#        class: %calaveracustomer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
